// Lista categoriilor
const categories = [
  {
    category_id: 1,
    name: "Books",
    description:
      "Explore an extensive collection of sci-fi novels and stories.",
  },
  {
    category_id: 2,
    name: "Movies",
    description:
      "A selection of the best sci-fi films from across the decades.",
  },
  {
    category_id: 3,
    name: "Action Figures",
    description: "Collectible sci-fi figures from iconic franchises.",
  },
  {
    category_id: 4,
    name: "Board Games",
    description: "Exciting sci-fi themed board games for enthusiasts.",
  },
  {
    category_id: 5,
    name: "Video Games",
    description: "Top sci-fi video games for immersive adventures.",
  },
];

// Array-ul constant al produselor constă din 36 de obiecte
const products = [
  {
    product_id: 1,
    name: "Chronicles of Lyria",
    details: "An epic fantasy adventure.",
    price: "29.99",
    stock: 45,
    discount: "10.00",
    category_id: 1,
  },
  {
    product_id: 2,
    name: "Mystery of Eldoria",
    details: "A thrilling detective novel.",
    price: "24.99",
    stock: 30,
    discount: "0",
    category_id: 1,
  },
  {
    product_id: 3,
    name: "Galactic Odyssey",
    details: "An epic space adventure movie.",
    price: "19.99",
    stock: 50,
    discount: "5.00",
    category_id: 2,
  },
  {
    product_id: 4,
    name: "Echoes of Eternity",
    details: "A cinematic masterpiece.",
    price: "22.99",
    stock: 60,
    discount: "0",
    category_id: 2,
  },
  {
    product_id: 5,
    name: "Knight Defender",
    details: "A heroic action figure.",
    price: "34.99",
    stock: 20,
    discount: "7.00",
    category_id: 3,
  },
  {
    product_id: 6,
    name: "Stealth Raider",
    details: "A legendary spy figure.",
    price: "39.99",
    stock: 15,
    discount: "0",
    category_id: 3,
  },
  {
    product_id: 7,
    name: "Quest for Avalon",
    details: "An adventurous board game.",
    price: "49.99",
    stock: 10,
    discount: "8.00",
    category_id: 4,
  },
  {
    product_id: 8,
    name: "Castle Siege",
    details: "A tactical board game experience.",
    price: "44.99",
    stock: 5,
    discount: "0",
    category_id: 4,
  },
  {
    product_id: 9,
    name: "Cyber Quest",
    details: "An immersive cyberpunk video game.",
    price: "59.99",
    stock: 25,
    discount: "15.00",
    category_id: 5,
  },
  {
    product_id: 10,
    name: "Dragon Realms",
    details: "A fantasy RPG game.",
    price: "54.99",
    stock: 30,
    discount: "0",
    category_id: 5,
  },
  {
    product_id: 11,
    name: "Whispers of the Forest",
    details: "A magical tale.",
    price: "27.99",
    stock: 40,
    discount: "8.00",
    category_id: 1,
  },
  {
    product_id: 12,
    name: "Legends of the Forgotten",
    details: "An enthralling fantasy novel.",
    price: "31.99",
    stock: 35,
    discount: "0",
    category_id: 1,
  },
  {
    product_id: 13,
    name: "Starlight Shadows",
    details: "A breathtaking sci-fi movie.",
    price: "18.99",
    stock: 55,
    discount: "4.00",
    category_id: 2,
  },
  {
    product_id: 14,
    name: "The Last Voyage",
    details: "A gripping space saga.",
    price: "21.99",
    stock: 65,
    discount: "0",
    category_id: 2,
  },
  {
    product_id: 15,
    name: "Titanium Warrior",
    details: "A stunning action figure.",
    price: "37.99",
    stock: 18,
    discount: "6.00",
    category_id: 3,
  },
  {
    product_id: 16,
    name: "Shadow Sentinel",
    details: "An iconic collectible.",
    price: "33.99",
    stock: 22,
    discount: "0",
    category_id: 3,
  },
  {
    product_id: 17,
    name: "Path of Heroes",
    details: "A thrilling board game.",
    price: "48.99",
    stock: 12,
    discount: "9.00",
    category_id: 4,
  },
  {
    product_id: 18,
    name: "Realm Conqueror",
    details: "A strategic board game for tacticians.",
    price: "45.99",
    stock: 8,
    discount: "0",
    category_id: 4,
  },
  {
    product_id: 19,
    name: "Neon Overdrive",
    details: "A high-speed racing game.",
    price: "58.99",
    stock: 20,
    discount: "14.00",
    category_id: 5,
  },
  {
    product_id: 20,
    name: "Star Crusade",
    details: "A tactical space combat game.",
    price: "56.99",
    stock: 28,
    discount: "0",
    category_id: 5,
  },
  {
    product_id: 21,
    name: "Eternal Light",
    details: "A mystical journey.",
    price: "30.99",
    stock: 42,
    discount: "7.00",
    category_id: 1,
  },
  {
    product_id: 22,
    name: "Guardians of Truth",
    details: "A compelling sci-fi book.",
    price: "28.99",
    stock: 33,
    discount: "0",
    category_id: 1,
  },
  {
    product_id: 23,
    name: "Frontier Horizons",
    details: "An inspiring movie.",
    price: "20.99",
    stock: 52,
    discount: "6.00",
    category_id: 2,
  },
  {
    product_id: 24,
    name: "Into the Unknown",
    details: "A timeless adventure movie.",
    price: "23.99",
    stock: 60,
    discount: "0",
    category_id: 2,
  },
  {
    product_id: 25,
    name: "Iron Commander",
    details: "A legendary collectible figure.",
    price: "36.99",
    stock: 16,
    discount: "5.00",
    category_id: 3,
  },
  {
    product_id: 26,
    name: "Blazing Phoenix",
    details: "A figure of fiery determination.",
    price: "32.99",
    stock: 19,
    discount: "0",
    category_id: 3,
  },
  {
    product_id: 27,
    name: "Tales of the Realm",
    details: "A captivating board game.",
    price: "47.99",
    stock: 14,
    discount: "10.00",
    category_id: 4,
  },
  {
    product_id: 28,
    name: "Battle of Kings",
    details: "An epic board game.",
    price: "46.99",
    stock: 9,
    discount: "0",
    category_id: 4,
  },
  {
    product_id: 29,
    name: "Solar Rift",
    details: "A groundbreaking video game.",
    price: "57.99",
    stock: 22,
    discount: "13.00",
    category_id: 5,
  },
  {
    product_id: 30,
    name: "Dark Horizon",
    details: "An intense space RPG.",
    price: "55.99",
    stock: 26,
    discount: "0",
    category_id: 5,
  },
  {
    product_id: 31,
    name: "Shadows of the Past",
    details: "A mysterious journey through time.",
    price: "26.99",
    stock: 44,
    discount: "9.00",
    category_id: 1,
  },
  {
    product_id: 32,
    name: "Winds of Change",
    details: "An epic saga.",
    price: "25.99",
    stock: 31,
    discount: "0",
    category_id: 1,
  },
  {
    product_id: 33,
    name: "Celestial Voyage",
    details: "A journey among the stars.",
    price: "19.49",
    stock: 54,
    discount: "7.00",
    category_id: 2,
  },
  {
    product_id: 34,
    name: "Dawn of Titans",
    details: "An unforgettable movie.",
    price: "21.49",
    stock: 62,
    discount: "0",
    category_id: 2,
  },
  {
    product_id: 35,
    name: "Steel Guardian",
    details: "A masterpiece for collectors.",
    price: "35.49",
    stock: 17,
    discount: "6.00",
    category_id: 3,
  },
  {
    product_id: 36,
    name: "Phantom Blade",
    details: "A highly detailed collectible.",
    price: "38.49",
    stock: 14,
    discount: "0",
    category_id: 3,
  },
];

// Exportă categoriile și produsele pentru utilizare ulterioară
export { categories, products };
