import { Fira_Code, Fredoka, Koulen } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Separator } from "@/components/ui/separator";

const firacode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={firacode.className}>
      <body className="antialiased">
        <Header />
        {children}
        <Separator />
        <Footer />
      </body>
    </html>
  );
}
